# Семинар 2

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [40]:
import numpy as np

In [41]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [42]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [44]:
vec.dtype

dtype('int64')

In [45]:
type(vec)

numpy.ndarray

Размер массива:

In [46]:
vec.shape

(3, 2)

Число осей:

In [47]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [48]:
np.sum(vec)

21

In [49]:
np.sum(vec, axis=0)

array([ 9, 12])

In [50]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [51]:
vec.sum()

21

Транспонируем массив:

In [52]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [53]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [54]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [55]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
vec.reshape(-1, 3) #-1 - автоматически посчитается нужное количество строк

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
vec.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Индексирование:

In [59]:
vec[:, 1]

array([2, 4, 6])

In [60]:
vec[2, :]

array([5, 6])

In [61]:
vec[1:2, 0] #правая граница (2) не включается

array([3])

In [62]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

Булевы массивы:

In [63]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [64]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [65]:
vec[vec % 2 == 0] #легко можно заменить присвоением

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [66]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [67]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [68]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [69]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [71]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [72]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [73]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [74]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [75]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [76]:
vec * vec ** 2 #(A*B - поэлементное умножение)

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [77]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [78]:
vec.dot(vec ** 2) #размеры не совпадают

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [79]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [80]:
vec @ (vec ** 2).T #@ - также матричное умножение

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [82]:
#справка по функции
?np.cross

In [83]:
vec * vec # поэлеметное, но не матричное умножение!

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [84]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
np.arange(3)

array([0, 1, 2])

In [86]:
vec + np.arange(3)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [87]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [90]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [91]:
np.random.rand(2, 3)

array([[0.2627807 , 0.0567926 , 0.42294795],
       [0.61335545, 0.68396699, 0.46844099]])

In [92]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [93]:
np.random.randn(3, 2) #стандартное нормальное распределение

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [94]:
np.random.normal(2, 1, size=(3,2)) #среднее 2 станд отклонение 1

array([[2.0169049 , 1.48501648],
       [2.24450929, 1.81068739],
       [4.67217242, 2.46480249]])

In [95]:
np.random.randint(5, 10, size=3)

array([6, 8, 5])

Почему вообще используют `numpy`?

In [96]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [97]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 22.3 s, sys: 268 ms, total: 22.5 s
Wall time: 23.3 s


In [98]:
%%time
C = A @ B

CPU times: user 4.38 ms, sys: 4.04 ms, total: 8.41 ms
Wall time: 16.1 ms


Операция присваивания

In [99]:
a = vec
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
vec[0,1] = 5
vec

array([[1, 5],
       [3, 4],
       [5, 6]])

In [101]:
a

array([[1, 5],
       [3, 4],
       [5, 6]])

In [102]:
b = vec.copy()

vec[2,1] = 10
vec

array([[ 1,  5],
       [ 3,  4],
       [ 5, 10]])

In [103]:
b

array([[1, 5],
       [3, 4],
       [5, 6]])

### Что ещё можно делать

Разворачивать массив

In [104]:
v = np.random.randint(5, 10, size=5)
v

array([7, 5, 7, 9, 9])

In [105]:
v[::-1]

array([9, 9, 7, 5, 7])

Читать информацию о функции

In [106]:
?np.random.randint

Перемешивать элементы массива

In [107]:
np.random.permutation(v)

array([7, 7, 9, 5, 9])

И многое другое...

### Задания для самостоятельного решения

1. Выведите квадраты первых десяти натуральных чисел

In [114]:
v = np.arange(1,11) ** 2
v

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

2. Выведите элементы массива, кратные трем.

In [108]:
v = np.random.randint(5, 10, size=5)
v[v % 3 == 0]

array([9])

3. Найдите максимальный нечетный элемент в массиве.

In [115]:
v[v % 2 != 0].max()

81

4. Замените все нечетные элементы массива на ваше любимое число.

In [134]:
v[v % 2 != 0] = 13
np.where(v % 2 != 0, 13, v)
v

array([ 13,   4,  13,  16,  13,  36,  13,  64,  13, 100])

5. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [123]:
n = 10
vec = np.arange(1, 2*n, 2)[::-1]
vec[vec % 2 != 0]
#np.arrange(2*n-1, 0, -2)

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

6. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [141]:
vec = np.array([0,1,2,3,4])
a = 7.2
vec[abs(vec-a).argmin()], vec[abs(vec-a).argmax()]



(4, 0)

7*. Вычислите первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [2]:
import numpy as np
arr =np.array([4,6,0,1])
np.append(arr / np.arange(len(arr),0,-1), -2)

array([ 1.,  2.,  0.,  1., -2.])

8*. Посчитайте первую производную для заданного полинома в заданной точке.

In [149]:
pows = np.arange(len(arr),0,-1)
point = 2
((arr * pows)[:-1:] * point ** pows[1:]).sum()

200

In [ ]:
#8. np.polyval(np.polyder([1., 2., 0., 1., -2.]), x)
#7. np.polyint([4, 6, 0, 1])